name: Python formatting PEP8
on: [push]

jobs:
  Python-PEP8:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip install flake8

      - name: Run checking
        run: |
          flake8 --extend-exclude bin,lib .
