name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: docker
    container:
      image: node:latest
      options: --tmpfs /tmp:exec

    steps:

      - name: Install Node
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest -v


  build-and-push:
    needs: test
    runs-on: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.f2n.me
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: code.f2n.me/finn/reminder:latest
