name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: docker
    container:
      image: node:latest
      options: --tmpfs /tmp:exec

    steps:

      - name: Install Node
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest -v


  build-amd64:
    needs: test
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_HOST: tcp://192.168.1.6:2376

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.f2n.me
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: code.f2n.me/finn/reminder:latest-amd64

  build-arm64:
    needs: test
    runs-on: docker-arm64
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_HOST: tcp://192.168.1.5:2376

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.f2n.me
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: code.f2n.me/finn/reminder:latest-arm64

  create-manifest:
    needs: [build-amd64, build-arm64]
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_HOST: tcp://192.168.1.6:2376

    steps:
      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.f2n.me
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create -t code.f2n.me/finn/reminder:latest \
            code.f2n.me/finn/reminder:latest-amd64 \
            code.f2n.me/finn/reminder:latest-arm64
