name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: docker
    container:
      image: node:latest
      options: --tmpfs /tmp:exec

    steps:

      - name: Install Node
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest -v


  build-and-push:
    needs: test
    runs-on: docker
    container:
      image: docker:24.0-dind
    steps:

      - name: Install node
        run: |
          apk update
          apk add nodejs npm git

      - name: Checkout
        uses: actions/checkout@v6

      - name: Start Docker daemon
        run: |
          dockerd-entrypoint.sh &
          # wait until docker daemon is ready
          until docker info; do sleep 1; done

      - name: Enable Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: code.f2n.me
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: code.f2n.me/finn/reminder:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect code.f2n.me/finn/reminder:latest
